import type { CanonicalReport } from "../core/model";

export function make_report(case_id = "case-a"): CanonicalReport {
  return {
    schema_version: "securemail.report/v1",
    manifest: {
      schema_version: "securemail.report/v1",
      generated_at: "2026-09-04T12:00:00Z",
      source_capture_sha256: "a".repeat(64),
      working_copy_availability: "unavailable",
      source_records: [{ kind: "case", availability: "present", identifier: case_id }],
      renderer: {
        html_renderer: "securemail.html/v1",
        pdf_renderer: "weasyprint",
        pdf_renderer_version: "69.0",
        template_name: "report.html.j2",
        template_sha256: "b".repeat(64),
        fonts: [
          {
            filename: "NotoSans-Regular.ttf",
            sha256: "9".repeat(64),
            family: "Noto Sans",
            weight: 400,
            style: "normal",
          },
        ],
      },
      signature: { availability: "unavailable", algorithm: null, timestamp: null },
      posture_summary: {
        risk_score: 90,
        assessment_state: "limited",
        finding_count: 1,
        unknown_count: 1,
        not_observable_count: 1,
      },
      configuration_digest: "c".repeat(64),
      analyzer_bundle_digest: "d".repeat(64),
      policy_profile: "ietf_current",
      policy_pack_version: "e".repeat(64),
      os_container_availability: "unavailable",
      case_id,
      artifact_hashes: [],
      dependency_versions: {},
      timezone: "UTC",
    },
    evidence: {
      schema_version: "v2",
      run_identity: {
        analysis_time: "2026-09-04T12:00:00Z",
        analyzer_bundle_digest: "d".repeat(64),
        capture_sha256: "a".repeat(64),
        configuration_digest: "c".repeat(64),
        normalization_schema_version: "v1",
        policy_pack_version: "e".repeat(64),
        policy_profile: "ietf_current",
      },
      capture_preflight: {
        packet_count: 10,
        file_time_precision: "nanosecond",
        truncated_packets_present: false,
      },
      flows: [
        {
          uid: "flow-1",
          orig: { host: "192.0.2.1", port: 40000 },
          resp: { host: "192.0.2.2", port: 25 },
          proto: "tcp",
          history: "ShAD",
          conn_state: "SF",
          missed_bytes: 0,
          orig_bytes: 10,
          resp_bytes: 20,
          reconstruction_quality: "complete",
          gap_bytes: 0,
          conflicting_byte_ranges: [],
          observed_conditions: [],
          evidence_state: "observed",
        },
      ],
      sessions: [],
      handshakes: [
        {
          uid: "tls-1",
          ssl_history: "Cs",
          established: true,
          resumed: false,
          hello_retry_request: false,
          visibility: "full",
          version: {
            selected: "TLSv10",
            client_supported_versions: [],
            evidence_state: "verified",
          },
          cipher_suite: { evidence_state: "observed" },
          key_exchange: { evidence_state: "indeterminate", psk_key_exchange_modes: [], source_fields: [] },
          server_certificate_state: "not_observable",
          certificate_verify_state: "not_observable",
          certificate_verify_signature: { evidence_state: "not_observable" },
          messages: [
            {
              kind: "server_hello",
              direction: "resp",
              history_letter: "s",
              frame_number: 6,
              evidence_state: "observed",
            },
          ],
          evidence_state: "observed",
        },
      ],
      certificates: [
        {
          uid: "tls-1",
          der_sha256: "8".repeat(64),
          chain_index: 0,
          role: "server",
          source_frames: [8],
          syntax_valid: true,
          evidence_state: "observed",
        },
      ],
      findings: [],
      policy_checks: [
        {
          check_id: "f".repeat(64),
          code: "TLS_OLD",
          category: "tls_handshake",
          protocol: "smtp",
          affected_endpoint: "192.0.2.2:25",
          record_type: "handshake",
          record_key: "tls-1",
          outcome: "fail",
          evidence_state: "verified",
          title: "Old TLS",
        },
      ],
      posture: {
        schema_version: "securemail.posture/v1",
        scoring_schema_version: "securemail.scoring/v1",
        risk_score: 90,
        assessment_state: "limited",
        coverage: {
          overall: {
            applicable_count: 3,
            passed_count: 1,
            failed_count: 1,
            unknown_count: 0,
            not_observable_count: 1,
          },
        },
        prioritized_findings: [
          {
            finding_id: "1".repeat(64),
            code: "TLS_OLD",
            outcome: "negative",
            title: "Old TLS",
            rationale: "TLS 1.0 negotiated",
            remediation_id: "rem.tls",
            severity: "high",
            evaluation_state: "verified",
            basis_state: "verified",
            policy_profile: "ietf_current",
            policy_pack_version: "e".repeat(64),
            rule_effective_from: "2018-01-01",
            policy_evaluation_time: "2026-09-04T12:00:00Z",
            affected_endpoint: "192.0.2.2:25",
            recurrence_count: 1,
            unique_occurrences: 1,
            contributing_finding_ids: ["1".repeat(64)],
            contributing_occurrences: [
              {
                finding_id: "1".repeat(64),
                record_type: "handshake",
                record_key: "tls-1",
              },
            ],
            evidence_references: [
              {
                record_type: "handshake",
                record_key: "tls-1",
                field_path: "version.selected",
                frame_number: 6,
                evidence_state: "verified",
              },
            ],
            score: 90,
            scoring_schema_version: "securemail.scoring/v1",
            components: {
              severity: 50,
              confidence: 20,
              exposure: 10,
              recurrence: 0,
              asset_criticality: 5,
              blast_radius: 5,
            },
            exposure: "public",
            asset_criticality: "critical",
            blast_radius: "organization",
            standards: [],
          },
        ],
      },
    },
    limitations: {
      truncated_packets_present: false,
      incomplete_flow_count: 0,
      conflicting_flow_count: 0,
      not_observable_certificate_count: 1,
      unknown_check_count: 0,
      not_observable_check_count: 1,
      notes: [],
    },
    advisory: { present: false, items: [] },
    analyst_conclusions: { present: false, notes: [] },
    exceptions: [],
    stage_errors: [],
    suppressed_findings: [],
  };
}
